# Generated by Django 4.2.2 on 2025-05-29 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_leave_apply_leave'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apply_Leave',
        ),
    ]
